version: "3.7"
services:
  web:
    image: php: latest
    depends_on: 
    - mysql
  mysql:
    image: mysql:5.7
  proxy:
    image: nginx:1.15.6
    depends_on:
    - web
  pma:
    image: phpmyadmin:latest
    depends_on:
      - mysql
	  